### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by krishnaadithya** [RViMLab/MICCAI2021_Cataract_semantic_segmentation#1]

**Comment by TheoPis** [comment]
Hi,
the dataset can be downloaded from the challenge website : https://cataracts-semantic-segmentation2020.grand-challenge.org/
one needs to register to request access to the dataset from the challenge organizers.
Also more information about the dataset can be found in this paper by the organizers: https://www.sciencedirect.com/science/article/pii/S1361841521000992#sec0013 
Hope this helps.

**Comment by felixholm** [comment]
Hi, is there another way to access the dataset? I requested access a while ago here https://cataracts-semantic-segmentation2020.grand-challenge.org/, but I got no response.

Thanks in advance for your help.
